obj-$(CONFIG_MMI_PARALLEL_CHARGER_IIO) += mmi_parallel_charger_iio.o
mmi_parallel_charger_iio-objs += mmi_charger_class.o
mmi_parallel_charger_iio-objs += mmi_charger_core.o
mmi_parallel_charger_iio-objs += mmi_charger_pump_policy.o
mmi_parallel_charger_iio-objs += mmi_cp_charger.o
mmi_parallel_charger_iio-objs += qpnp_pmic_charger.o
mmi_parallel_charger_iio-objs += mmi_qc3p.o
mmi_parallel_charger_iio-objs += mmi_qc3p_cp_policy.o
